### ISSUE TITLE
Low contrast Ratio in social icons

### ISSUE THREAD

**Issue by VikashPR** [Kanishk-K-U/Kanishk-K-U#2]
![Screenshot 2022-03-10 at 8 08 01 AM](https://user-images.githubusercontent.com/69889418/157577495-bc08b0a9-9b65-40ed-bebd-467bd7bb44f3.png)
Contrast ratio of the social icons is very low in dark more, try to use colourful icons which will look better in both light more and dark more.

**Comment by Kanishk-K-U** [comment]
Sure!! Thanks
